### PR TITLE
Bill Processing Org Adjustment

### PR DESCRIPTION
**Pull request by jagatfx**
- generic parent parser.js file that requires in available bill parsers for different bill types
- individual parsers use a canProcessBill() function to say whether they can parse a given bill
- individual parsers use a generic processStatementPage() function and still get pages from parent parser.js
- individual parsers use one or more processors for parsing bill statement pages with generic canProcessPage() and parsePage() functions so the parent can be unaware of the specific processors used
- the exemplar verizon parser includes one implementation of a processor (current-charges-summary.js) and another shell processor to be implemented (statement-of-account.js)
- state is stored in an object that is passed around as minimally as possible, billSummary, with no more use of global state

### CODE REVIEW

**Comment by jagatfx** [comment]
@nnance could you take a look and test this out

**Comment by nnance** [comment]
@jagatfx I pushed a couple of changes that converts the parser arrays to highland streams.  The next step would do be to use the node filesystem to dynamically load the parser modules from the file system which the results can then be used as a highland stream based on my changes and will make the entire process async.

In general I really like the approach I just have a couple of concerns:
1. as we pass this data structure around during the parsing we need to be careful and make sure most of the functions are only process the bill and returns results and limit the management of the data structure to as few functions as possible.
2. What about the types of page parsers that might need to get data from many different pages?  Would it just have the ability to do the necessary parsing and update the data structure from page to page?

**Comment by nnance** [comment]
@jagatfx +1 for a merge to master if you are ready

**Comment by jagatfx** [comment]
@nnance thanks for improvements. +1 on your next step suggestion. 

I too have concerns about state passing and management. I do not think this technique is 100% there but is workable and usable in the near-term. I agree fully that we need to enforce some constraints to keep this useful. 

For (2), I thought about page to page parsing (needing to get data from many different pages). I think it could be like Map Reduce where workers process individual page streams and then a reduction operation occurs (such as aggregate operation).

**Comment by jagatfx** [comment]
Gonna merge now and we can discuss new changes in new branches.

**Pull request merged**
